// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjuLIxkfVSORGWLpPlnmjgOUEt1O3wUjo',
    appId: '1:158344800093:web:676c0a77f13116b54c6ab4',
    messagingSenderId: '158344800093',
    projectId: 'subhash-inventory-app',
    authDomain: 'subhash-inventory-app.firebaseapp.com',
    storageBucket: 'subhash-inventory-app.appspot.com',
    measurementId: 'G-EG3EGRP648',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAyv4jMwDnUJ0ypkDdp6ghP10Vyqlu40w',
    appId: '1:158344800093:android:948a936146ecfcdb4c6ab4',
    messagingSenderId: '158344800093',
    projectId: 'subhash-inventory-app',
    storageBucket: 'subhash-inventory-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbPARCmNRSEQgQts7P64WIiQkgFLACOHQ',
    appId: '1:158344800093:ios:453c2b1ca82ffe994c6ab4',
    messagingSenderId: '158344800093',
    projectId: 'subhash-inventory-app',
    storageBucket: 'subhash-inventory-app.appspot.com',
    iosBundleId: 'com.example.inventoryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbPARCmNRSEQgQts7P64WIiQkgFLACOHQ',
    appId: '1:158344800093:ios:7eaa6034fcb725294c6ab4',
    messagingSenderId: '158344800093',
    projectId: 'subhash-inventory-app',
    storageBucket: 'subhash-inventory-app.appspot.com',
    iosBundleId: 'com.example.inventoryApp.RunnerTests',
  );
}
